<?php
use yii\helpers\Url;
use kartik\export\ExportMenu;
use kartik\grid\GridView;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    // [
    // //'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'codigo',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'nombre',
        'label'=>'Nombre del Hospital',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'direccion',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'telefono',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'puede_dializar',
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pe_d',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'esta_conectado_planta_electrica_del_hospital',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pe_diesel',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'dia_tot_pe_ope',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'dia_tot_pe_ino',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_aceite',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_cantidad_aceite_requerido',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_tipo_aceite_requerido',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_dissel',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_cantidad_dissel_requerido',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_bateria',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_cantidad_baterias_requeridas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_nivel_dissel_restante',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_refrigerante_necesidad',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_nivel_refrigerante_restante',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_nivel_aceite_restante',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_tecnico_de_guardia',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_electrica_telefono_tecnico_guardia',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_disponible',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'capacidad_tanque',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'maquinas_operativas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'maquinas_inoperativas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'total_maquinas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pacientes_que_atiende',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'planta_de_osmosis',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'persona_responsable',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'cod_establecimiento_salud',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'establecimiento_de_salud',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_capacidad_total_lts',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_porcentaje_de_llenado',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_gasto_diario',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_reservas_lts',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_tanques_para_consumo_1500_lts',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'agua_por_tuberia',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones_agua',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'total_ambulancias',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ambulancias_de_apoyo_con',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ambulancias_con_soporte_vital',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones_ambulancias',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'camas_operativas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pacientes_criticos_adultos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pacientes_criticos_ninos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'uti_neonatal_pacientes',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'utineonatal_cupos_disponibles',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'uti_camas_operativas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'uti_camas_disponibles',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'quirofanos_emergencias_operativos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'quirofanos_emergencias_inoperativos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'equipo_de_guardia',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'total_muertes_maternas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'detalle_muerte_materna',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'servicio_hemoderivados',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'servicio_hemoderivados_operativos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones_movimiento',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'pe_ser_gen',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_total_pe_op',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_tot_pe_ino',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'_ser_gen_pe_ace',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_can_ace',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_pe_tip_ace',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_diesel_pe',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_diesel_re_pe',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_pe_bat',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_pe_bat_req',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_pe_di_res',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_pe_ref_nec',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_ref_res',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_race_res',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_tec_pe',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'ser_gen_tec_tlf',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'refrigeracion_de_alimentos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'gases_medicinales_operativo',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'gases_medicinales_reservas',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'equipos_esterilizacion',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'desechos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones_desechos',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'observaciones_serv_gen',
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'estado',
     ],
    ['class' => 'kartik\grid\ActionColumn', 'urlCreator'=>function(){return '#';}]
   // [
    //    'class' => 'kartik\grid\ActionColumn',
    //    'dropdown' => false,
    //    'vAlign'=>'middle',
    //    'urlCreator' => function($action, $model, $key, $index) { 
    //            return Url::to([$action,'id'=>$key]);
    //    },
    //    'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
    //    'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
    //    'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
    //                      'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                      'data-request-method'=>'post',
    //                      'data-toggle'=>'tooltip',
    //                     'data-confirm-title'=>'Are you sure?',
    //                      'data-confirm-message'=>'Are you sure want to delete this item'], 
    //],

];   